### PR TITLE
fix: installer throwing error

### PR DESCRIPTION
**Pull request by latekvo**
This PR fixes regression introduced in #162:

```
◇  Add Argent tools to editor auto-approve lists? - recommended
│  Yes
node:internal/modules/cjs/loader:1459
  throw err;
  ^

Error: Cannot find module '/Users/ignacylatka/.npm/_npx/9bf42f550c32750c/node_modules/@swmansion/argent/tool-server.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
    at Module._load (node:internal/modules/cjs/loader:1242:25)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v24.14.1

```

### Root cause

`packages/argent-installer/src/mcp-configs.ts:22` resolves the bundled tool-server with:

```ts
path.join(import.meta.dirname, "..", "tool-server.cjs")
```

That was correct in the pre-#162 layout where the file lived at `packages/mcp/dist/cli/mcp-configs.js` and `..` stepped from `dist/cli/` to `dist/`. 
After the refactor the file is inlined into `packages/argent/dist/installer.mjs` — a direct **sibling** of `dist/tool-server.cjs` — so `..` now climbs one level too far and resolves to `<pkg>/tool-server.cjs`.

The codex adapter's `addAllowlist`/`removeAllowlist` calls `getAvailableToolIds()` → `execFileSync("node", [TOOL_SERVER_BUNDLE, "-t"])`, which is where the broken path is dereferenced.

### Fix

Drop the `..`. Existing `packages/argent/src/bundled-paths.ts:7` already uses the sibling form, so this aligns the two.

### CODE REVIEW

File: packages/argent-installer/src/mcp-configs.ts [hunk 1]
```diff
@@ -10,18 +10,18 @@ import {
...
   writeToml,
   readYaml,
   writeYaml,
-  editJsoncFile,
 } from "./utils.js";
 import { isMap } from "yaml";
 
-const TOOL_SERVER_BUNDLE = path.join(import.meta.dirname, "..", "tool-server.cjs");
+// `installer.mjs` and `tool-server.cjs` are bundled side-by-side into the
+// published package's `dist/` directory by scripts/bundle-tools.cjs.
```
Comment (latekvo) [inline packages/argent-installer/src/mcp-configs.ts]:
```suggestion
```

**Comment by latekvo** [comment]
Tested, seems to work.

**Review by filip131311 — APPROVED** [review]
nice
